### ISSUE TITLE
"Uncaught TypeError: Must be a file URL" in encoding_event_stream_test when trying to use module

### ISSUE THREAD

**Issue by markmals** [c4spar/deno-fast-forward#14]
I'm currently trying to use this module in my own script. When trying to run the simplest of tests on my script that uses fast forward, I get the following error:

```typescript
import { ffmpeg } from "https://deno.land/x/fast_forward@0.1.4/mod.ts"
import { assert } from "https://deno.land/std@0.106.0/testing/asserts.ts"
Deno.test("fast_forward runs", async () => {
    await ffmpeg("<path to mkv>")
        .output("<path to mp4>")
        .encode()

    assert(true, "works")
})
```

```shell
error: Uncaught TypeError: Must be a file URL.
    throw new TypeError("Must be a file URL.");
          ^
    at fromFileUrl (https://deno.land/std@0.103.0/path/posix.ts:487:11)
    at https://deno.land/x/fast_forward@0.1.4/encoding_event_stream_test.ts:21:33
The terminal process "deno 'test', '--allow-all', '--unstable', '--filter', 'fast_forward runs', '.../transcodeDir_test.ts'" terminated with exit code: 1.
```

I'm new to Deno, so I might be overlooking something, but nothing about my input should be causing this error, especially in a global constant in a test file. I'm using `deno 1.13.2`.

**Comment by SnowGuest** [comment]
I also encountered this problem

**Comment by denizdogan** [comment]
If you import `ffmpeg.ts` instead of `mod.ts`, it works. For some reason the author of this module decided to import unit tests in `mod.ts`. Maybe this is an old Deno convention?

**Comment by brzostekd** [comment]
Thank you @denizdogan. Too bad that it won't be fixed. 🤷‍♂️
